// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyjbbsWE4234djxyge6L3xjjyRtcAPKus',
    appId: '1:1078425295491:web:f9b18c10fd66dba43d99b6',
    messagingSenderId: '1078425295491',
    projectId: 'myapp2-fc5b0',
    authDomain: 'myapp2-fc5b0.firebaseapp.com',
    storageBucket: 'myapp2-fc5b0.appspot.com',
    measurementId: 'G-72WS1G3X5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTUsEb4tbnUN1pydcLGbYV6tyikjpwKcY',
    appId: '1:1078425295491:android:fc373aeb55587b313d99b6',
    messagingSenderId: '1078425295491',
    projectId: 'myapp2-fc5b0',
    storageBucket: 'myapp2-fc5b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZDcJTGKf7QzC4etFdsZqB1PI-6pwlmJY',
    appId: '1:1078425295491:ios:397995f47c54b8b23d99b6',
    messagingSenderId: '1078425295491',
    projectId: 'myapp2-fc5b0',
    storageBucket: 'myapp2-fc5b0.appspot.com',
    iosClientId: '1078425295491-7h28ie2230hra3oovrbu0f6ike3p4dt4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZDcJTGKf7QzC4etFdsZqB1PI-6pwlmJY',
    appId: '1:1078425295491:ios:397995f47c54b8b23d99b6',
    messagingSenderId: '1078425295491',
    projectId: 'myapp2-fc5b0',
    storageBucket: 'myapp2-fc5b0.appspot.com',
    iosClientId: '1078425295491-7h28ie2230hra3oovrbu0f6ike3p4dt4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
